- type: wikiquote
  people: Romanian
  url: https://en.wikiquote.org/wiki/Romanian_proverbs
- type: wikiquote
  people: English
  url: https://en.wikiquote.org/wiki/English_proverbs
- type: wikiquote
  people: Greek
  url: https://en.wikiquote.org/wiki/Greek_proverbs
- type: wikiquote
  people: Turkish
  url: https://en.wikiquote.org/wiki/Turkish_proverbs
- type: wikiquote
  people: Italian
  url: https://en.wikiquote.org/wiki/Italian_proverbs
- type: wikiquote
  people: Spanish
  url: https://en.wikiquote.org/wiki/Spanish_proverbs
- type: wikiquote
  people: French
  url: https://en.wikiquote.org/wiki/French_proverbs
- type: wikiquote
  people: German
  url: https://en.wikiquote.org/wiki/German_proverbs
- type: wikiquote
  people: Dutch
  url: https://en.wikiquote.org/wiki/Dutch_proverbs
- type: wikiquote
  people: Portuguese
  url: https://en.wikiquote.org/wiki/Portuguese_proverbs
- type: wikiquote
  people: Russian
  url: https://en.wikiquote.org/wiki/Russian_proverbs
- type: wikiquote
  people: Ukrainian
  url: https://en.wikiquote.org/wiki/Ukrainian_proverbs
- type: wikiquote
  people: Polish
  url: https://en.wikiquote.org/wiki/Polish_proverbs
- type: wikiquote
  people: Czech
  url: https://en.wikiquote.org/wiki/Czech_proverbs
- type: wikiquote
  people: Slovak
  url: https://en.wikiquote.org/wiki/Slovak_proverbs
- type: wikiquote
  people: Hungarian
  url: https://en.wikiquote.org/wiki/Hungarian_proverbs
- type: wikiquote
  people: Bulgarian
  url: https://en.wikiquote.org/wiki/Bulgarian_proverbs
- type: wikiquote
  people: Serbian
  url: https://en.wikiquote.org/wiki/Serbian_proverbs
- type: wikiquote
  people: Croatian
  url: https://en.wikiquote.org/wiki/Croatian_proverbs
- type: wikiquote
  people: Bosnian
  url: https://en.wikiquote.org/wiki/Bosnian_proverbs
- type: wikiquote
  people: Slovenian
  url: https://en.wikiquote.org/wiki/Slovenian_proverbs
- type: wikiquote
  people: Macedonian
  url: https://en.wikiquote.org/wiki/Macedonian_proverbs
- type: wikiquote
  people: Albanian
  url: https://en.wikiquote.org/wiki/Albanian_proverbs
- type: wikiquote
  people: Armenian
  url: https://en.wikiquote.org/wiki/Armenian_proverbs
- type: wikiquote
  people: Georgian
  url: https://en.wikiquote.org/wiki/Georgian_proverbs
- type: wikiquote
  people: Lithuanian
  url: https://en.wikiquote.org/wiki/Lithuanian_proverbs
- type: wikiquote
  people: Latvian
  url: https://en.wikiquote.org/wiki/Latvian_proverbs
- type: wikiquote
  people: Estonian
  url: https://en.wikiquote.org/wiki/Estonian_proverbs
- type: wikiquote
  people: Finnish
  url: https://en.wikiquote.org/wiki/Finnish_proverbs
- type: wikiquote
  people: Swedish
  url: https://en.wikiquote.org/wiki/Swedish_proverbs
- type: wikiquote
  people: Norwegian
  url: https://en.wikiquote.org/wiki/Norwegian_proverbs
- type: wikiquote
  people: Danish
  url: https://en.wikiquote.org/wiki/Danish_proverbs
- type: wikiquote
  people: Icelandic
  url: https://en.wikiquote.org/wiki/Icelandic_proverbs
- type: wikiquote
  people: Irish
  url: https://en.wikiquote.org/wiki/Irish_proverbs
- type: wikiquote
  people: Scottish Gaelic
  url: https://en.wikiquote.org/wiki/Scottish_Gaelic_proverbs
- type: wikiquote
  people: Welsh
  url: https://en.wikiquote.org/wiki/Welsh_proverbs
- type: wikiquote
  people: Basque
  url: https://en.wikiquote.org/wiki/Basque_proverbs
- type: wikiquote
  people: Catalan
  url: https://en.wikiquote.org/wiki/Catalan_proverbs
- type: wikiquote
  people: Galician
  url: https://en.wikiquote.org/wiki/Galician_proverbs
- type: wikiquote
  people: Portuguese (Brazil)
  url: https://en.wikiquote.org/wiki/Portuguese_(Brazil)_proverbs
- type: wikiquote
  people: Quechua
  url: https://en.wikiquote.org/wiki/Quechua_proverbs
- type: wikiquote
  people: Arabic
  url: https://en.wikiquote.org/wiki/Arabic_proverbs
- type: wikiquote
  people: Persian
  url: https://en.wikiquote.org/wiki/Persian_proverbs
- type: wikiquote
  people: Hebrew
  url: https://en.wikiquote.org/wiki/Hebrew_proverbs
- type: wikiquote
  people: Kurdish
  url: https://en.wikiquote.org/wiki/Kurdish_proverbs
- type: wikiquote
  people: Urdu
  url: https://en.wikiquote.org/wiki/Urdu_proverbs
- type: wikiquote
  people: Hindi
  url: https://en.wikiquote.org/wiki/Hindi_proverbs
- type: wikiquote
  people: Bengali
  url: https://en.wikiquote.org/wiki/Bengali_proverbs
- type: wikiquote
  people: Punjabi
  url: https://en.wikiquote.org/wiki/Punjabi_proverbs
- type: wikiquote
  people: Marathi
  url: https://en.wikiquote.org/wiki/Marathi_proverbs
- type: wikiquote
  people: Gujarati
  url: https://en.wikiquote.org/wiki/Gujarati_proverbs
- type: wikiquote
  people: Tamil
  url: https://en.wikiquote.org/wiki/Tamil_proverbs
- type: wikiquote
  people: Telugu
  url: https://en.wikiquote.org/wiki/Telugu_proverbs
- type: wikiquote
  people: Malayalam
  url: https://en.wikiquote.org/wiki/Malayalam_proverbs
- type: wikiquote
  people: Sinhala
  url: https://en.wikiquote.org/wiki/Sinhala_proverbs
- type: wikiquote
  people: Thai
  url: https://en.wikiquote.org/wiki/Thai_proverbs
- type: wikiquote
  people: Lao
  url: https://en.wikiquote.org/wiki/Lao_proverbs
- type: wikiquote
  people: Vietnamese
  url: https://en.wikiquote.org/wiki/Vietnamese_proverbs
- type: wikiquote
  people: Khmer
  url: https://en.wikiquote.org/wiki/Khmer_proverbs
- type: wikiquote
  people: Indonesian
  url: https://en.wikiquote.org/wiki/Indonesian_proverbs
- type: wikiquote
  people: Malay
  url: https://en.wikiquote.org/wiki/Malay_proverbs
- type: wikiquote
  people: Javanese
  url: https://en.wikiquote.org/wiki/Javanese_proverbs
- type: wikiquote
  people: Sundanese
  url: https://en.wikiquote.org/wiki/Sundanese_proverbs
- type: wikiquote
  people: Filipino
  url: https://en.wikiquote.org/wiki/Filipino_proverbs
- type: wikiquote
  people: Chinese
  url: https://en.wikiquote.org/wiki/Chinese_proverbs
- type: wikiquote
  people: Japanese
  url: https://en.wikiquote.org/wiki/Japanese_proverbs
- type: wikiquote
  people: Korean
  url: https://en.wikiquote.org/wiki/Korean_proverbs
- type: wikiquote
  people: Mongolian
  url: https://en.wikiquote.org/wiki/Mongolian_proverbs
- type: wikiquote
  people: Tibetan
  url: https://en.wikiquote.org/wiki/Tibetan_proverbs
- type: wikiquote
  people: Burmese
  url: https://en.wikiquote.org/wiki/Burmese_proverbs
- type: wikiquote
  people: Amharic
  url: https://en.wikiquote.org/wiki/Amharic_proverbs
- type: wikiquote
  people: Somali
  url: https://en.wikiquote.org/wiki/Somali_proverbs
- type: wikiquote
  people: Oromo
  url: https://en.wikiquote.org/wiki/Oromo_proverbs
- type: wikiquote
  people: Swahili
  url: https://en.wikiquote.org/wiki/Swahili_proverbs
- type: wikiquote
  people: Yoruba
  url: https://en.wikiquote.org/wiki/Yoruba_proverbs
- type: wikiquote
  people: Hausa
  url: https://en.wikiquote.org/wiki/Hausa_proverbs
- type: wikiquote
  people: Igbo
  url: https://en.wikiquote.org/wiki/Igbo_proverbs
- type: wikiquote
  people: Zulu
  url: https://en.wikiquote.org/wiki/Zulu_proverbs
- type: wikiquote
  people: Xhosa
  url: https://en.wikiquote.org/wiki/Xhosa_proverbs
- type: wikiquote
  people: Shona
  url: https://en.wikiquote.org/wiki/Shona_proverbs
- type: wikiquote
  people: Maori
  url: https://en.wikiquote.org/wiki/Maori_proverbs
- type: wikiquote
  people: Samoan
  url: https://en.wikiquote.org/wiki/Samoan_proverbs
- type: wikiquote
  people: Tongan
  url: https://en.wikiquote.org/wiki/Tongan_proverbs
- type: wikiquote
  people: Hawaiian
  url: https://en.wikiquote.org/wiki/Hawaiian_proverbs
- type: wiktionary_category
  people: Romanian
  url: https://en.wiktionary.org/wiki/Category:Romanian_proverbs
- type: wiktionary_category
  people: English
  url: https://en.wiktionary.org/wiki/Category:English_proverbs
- type: wiktionary_category
  people: Greek
  url: https://en.wiktionary.org/wiki/Category:Greek_proverbs
- type: wiktionary_category
  people: Turkish
  url: https://en.wiktionary.org/wiki/Category:Turkish_proverbs
- type: wiktionary_category
  people: Italian
  url: https://en.wiktionary.org/wiki/Category:Italian_proverbs
- type: wiktionary_category
  people: Spanish
  url: https://en.wiktionary.org/wiki/Category:Spanish_proverbs
- type: wiktionary_category
  people: French
  url: https://en.wiktionary.org/wiki/Category:French_proverbs
- type: wiktionary_category
  people: German
  url: https://en.wiktionary.org/wiki/Category:German_proverbs
- type: wiktionary_category
  people: Dutch
  url: https://en.wiktionary.org/wiki/Category:Dutch_proverbs
- type: wiktionary_category
  people: Portuguese
  url: https://en.wiktionary.org/wiki/Category:Portuguese_proverbs
- type: wiktionary_category
  people: Russian
  url: https://en.wiktionary.org/wiki/Category:Russian_proverbs
- type: wiktionary_category
  people: Ukrainian
  url: https://en.wiktionary.org/wiki/Category:Ukrainian_proverbs
- type: wiktionary_category
  people: Polish
  url: https://en.wiktionary.org/wiki/Category:Polish_proverbs
- type: wiktionary_category
  people: Czech
  url: https://en.wiktionary.org/wiki/Category:Czech_proverbs
- type: wiktionary_category
  people: Slovak
  url: https://en.wiktionary.org/wiki/Category:Slovak_proverbs
- type: wiktionary_category
  people: Hungarian
  url: https://en.wiktionary.org/wiki/Category:Hungarian_proverbs
- type: wiktionary_category
  people: Bulgarian
  url: https://en.wiktionary.org/wiki/Category:Bulgarian_proverbs
- type: wiktionary_category
  people: Serbian
  url: https://en.wiktionary.org/wiki/Category:Serbian_proverbs
- type: wiktionary_category
  people: Croatian
  url: https://en.wiktionary.org/wiki/Category:Croatian_proverbs
- type: wiktionary_category
  people: Bosnian
  url: https://en.wiktionary.org/wiki/Category:Bosnian_proverbs
- type: wiktionary_category
  people: Slovenian
  url: https://en.wiktionary.org/wiki/Category:Slovenian_proverbs
- type: wiktionary_category
  people: Macedonian
  url: https://en.wiktionary.org/wiki/Category:Macedonian_proverbs
- type: wiktionary_category
  people: Albanian
  url: https://en.wiktionary.org/wiki/Category:Albanian_proverbs
- type: wiktionary_category
  people: Armenian
  url: https://en.wiktionary.org/wiki/Category:Armenian_proverbs
- type: wiktionary_category
  people: Georgian
  url: https://en.wiktionary.org/wiki/Category:Georgian_proverbs
- type: wiktionary_category
  people: Lithuanian
  url: https://en.wiktionary.org/wiki/Category:Lithuanian_proverbs
- type: wiktionary_category
  people: Latvian
  url: https://en.wiktionary.org/wiki/Category:Latvian_proverbs
- type: wiktionary_category
  people: Estonian
  url: https://en.wiktionary.org/wiki/Category:Estonian_proverbs
- type: wiktionary_category
  people: Finnish
  url: https://en.wiktionary.org/wiki/Category:Finnish_proverbs
- type: wiktionary_category
  people: Swedish
  url: https://en.wiktionary.org/wiki/Category:Swedish_proverbs
- type: wiktionary_category
  people: Norwegian
  url: https://en.wiktionary.org/wiki/Category:Norwegian_proverbs
- type: wiktionary_category
  people: Danish
  url: https://en.wiktionary.org/wiki/Category:Danish_proverbs
- type: wiktionary_category
  people: Icelandic
  url: https://en.wiktionary.org/wiki/Category:Icelandic_proverbs
- type: wiktionary_category
  people: Irish
  url: https://en.wiktionary.org/wiki/Category:Irish_proverbs
- type: wiktionary_category
  people: Scottish Gaelic
  url: https://en.wiktionary.org/wiki/Category:Scottish_Gaelic_proverbs
- type: wiktionary_category
  people: Welsh
  url: https://en.wiktionary.org/wiki/Category:Welsh_proverbs
- type: wiktionary_category
  people: Basque
  url: https://en.wiktionary.org/wiki/Category:Basque_proverbs
- type: wiktionary_category
  people: Catalan
  url: https://en.wiktionary.org/wiki/Category:Catalan_proverbs
- type: wiktionary_category
  people: Galician
  url: https://en.wiktionary.org/wiki/Category:Galician_proverbs
- type: wiktionary_category
  people: Portuguese (Brazil)
  url: https://en.wiktionary.org/wiki/Category:Portuguese_(Brazil)_proverbs
- type: wiktionary_category
  people: Quechua
  url: https://en.wiktionary.org/wiki/Category:Quechua_proverbs
- type: wiktionary_category
  people: Arabic
  url: https://en.wiktionary.org/wiki/Category:Arabic_proverbs
- type: wiktionary_category
  people: Persian
  url: https://en.wiktionary.org/wiki/Category:Persian_proverbs
- type: wiktionary_category
  people: Hebrew
  url: https://en.wiktionary.org/wiki/Category:Hebrew_proverbs
- type: wiktionary_category
  people: Kurdish
  url: https://en.wiktionary.org/wiki/Category:Kurdish_proverbs
- type: wiktionary_category
  people: Urdu
  url: https://en.wiktionary.org/wiki/Category:Urdu_proverbs
- type: wiktionary_category
  people: Hindi
  url: https://en.wiktionary.org/wiki/Category:Hindi_proverbs
- type: wiktionary_category
  people: Bengali
  url: https://en.wiktionary.org/wiki/Category:Bengali_proverbs
- type: wiktionary_category
  people: Punjabi
  url: https://en.wiktionary.org/wiki/Category:Punjabi_proverbs
- type: wiktionary_category
  people: Marathi
  url: https://en.wiktionary.org/wiki/Category:Marathi_proverbs
- type: wiktionary_category
  people: Gujarati
  url: https://en.wiktionary.org/wiki/Category:Gujarati_proverbs
- type: wiktionary_category
  people: Tamil
  url: https://en.wiktionary.org/wiki/Category:Tamil_proverbs
- type: wiktionary_category
  people: Telugu
  url: https://en.wiktionary.org/wiki/Category:Telugu_proverbs
- type: wiktionary_category
  people: Malayalam
  url: https://en.wiktionary.org/wiki/Category:Malayalam_proverbs
- type: wiktionary_category
  people: Sinhala
  url: https://en.wiktionary.org/wiki/Category:Sinhala_proverbs
- type: wiktionary_category
  people: Thai
  url: https://en.wiktionary.org/wiki/Category:Thai_proverbs
- type: wiktionary_category
  people: Lao
  url: https://en.wiktionary.org/wiki/Category:Lao_proverbs
- type: wiktionary_category
  people: Vietnamese
  url: https://en.wiktionary.org/wiki/Category:Vietnamese_proverbs
- type: wiktionary_category
  people: Khmer
  url: https://en.wiktionary.org/wiki/Category:Khmer_proverbs
- type: wiktionary_category
  people: Indonesian
  url: https://en.wiktionary.org/wiki/Category:Indonesian_proverbs
- type: wiktionary_category
  people: Malay
  url: https://en.wiktionary.org/wiki/Category:Malay_proverbs
- type: wiktionary_category
  people: Javanese
  url: https://en.wiktionary.org/wiki/Category:Javanese_proverbs
- type: wiktionary_category
  people: Sundanese
  url: https://en.wiktionary.org/wiki/Category:Sundanese_proverbs
- type: wiktionary_category
  people: Filipino
  url: https://en.wiktionary.org/wiki/Category:Filipino_proverbs
- type: wiktionary_category
  people: Chinese
  url: https://en.wiktionary.org/wiki/Category:Chinese_proverbs
- type: wiktionary_category
  people: Japanese
  url: https://en.wiktionary.org/wiki/Category:Japanese_proverbs
- type: wiktionary_category
  people: Korean
  url: https://en.wiktionary.org/wiki/Category:Korean_proverbs
- type: wiktionary_category
  people: Mongolian
  url: https://en.wiktionary.org/wiki/Category:Mongolian_proverbs
- type: wiktionary_category
  people: Tibetan
  url: https://en.wiktionary.org/wiki/Category:Tibetan_proverbs
- type: wiktionary_category
  people: Burmese
  url: https://en.wiktionary.org/wiki/Category:Burmese_proverbs
- type: wiktionary_category
  people: Amharic
  url: https://en.wiktionary.org/wiki/Category:Amharic_proverbs
- type: wiktionary_category
  people: Somali
  url: https://en.wiktionary.org/wiki/Category:Somali_proverbs
- type: wiktionary_category
  people: Oromo
  url: https://en.wiktionary.org/wiki/Category:Oromo_proverbs
- type: wiktionary_category
  people: Swahili
  url: https://en.wiktionary.org/wiki/Category:Swahili_proverbs
- type: wiktionary_category
  people: Yoruba
  url: https://en.wiktionary.org/wiki/Category:Yoruba_proverbs
- type: wiktionary_category
  people: Hausa
  url: https://en.wiktionary.org/wiki/Category:Hausa_proverbs
- type: wiktionary_category
  people: Igbo
  url: https://en.wiktionary.org/wiki/Category:Igbo_proverbs
- type: wiktionary_category
  people: Zulu
  url: https://en.wiktionary.org/wiki/Category:Zulu_proverbs
- type: wiktionary_category
  people: Xhosa
  url: https://en.wiktionary.org/wiki/Category:Xhosa_proverbs
- type: wiktionary_category
  people: Shona
  url: https://en.wiktionary.org/wiki/Category:Shona_proverbs
- type: wiktionary_category
  people: Maori
  url: https://en.wiktionary.org/wiki/Category:Maori_proverbs
- type: wiktionary_category
  people: Samoan
  url: https://en.wiktionary.org/wiki/Category:Samoan_proverbs
- type: wiktionary_category
  people: Tongan
  url: https://en.wiktionary.org/wiki/Category:Tongan_proverbs
- type: wiktionary_category
  people: Hawaiian
  url: https://en.wiktionary.org/wiki/Category:Hawaiian_proverbs
- type: wiktionary_appendix
  people: English
  url: https://en.wiktionary.org/wiki/Appendix:English_proverbs
- type: gutenberg_html
  people: Multi (EU)
  url: https://www.gutenberg.org/files/51090/51090-h/51090-h.htm
- type: internet_archive_html
  people: English
  url: https://archive.org/details/rayenglishproverbs2ed
