- people: English
  type: wikiquote
  url: https://en.wikiquote.org/wiki/English_proverbs
- people: Romanian
  type: wikiquote
  url: https://en.wikiquote.org/wiki/Romanian_proverbs
- people: Japanese
  type: wikiquote
  url: https://en.wikiquote.org/wiki/Japanese_proverbs
